const ALERT='ALERT'
const REFETCH_CHATS='REFETCH_CHATS'
const NEW_ATTACHMENTS='NEW_ATTACHMENTS'
const NEW_MESSAGES_ALERT='NEW_MESSAGES_ALERT'
const NEW_MESSAGE='NEW_MESSAGE'
const NEW_REQUEST='NEW_REQUEST'
const START_TYPING="START_TYPING"
const STOP_TYPING="STOP_TYPING"

const CHAT_JOINED="CHAT_JOINED"
const CHAT_LEAVED="CHAT_LEAVED"
const ONLINE_USERS="ONLINE_USERS"
const CALLING="CALLING"
const SOMEONE_CALLING="SOMEONE_CALLING"
const CALL_ACCEPTED="CALL_ACCEPTED"
const CALL_REJECTED="CALL_REJECTED"
const TAKE_OFFER="TAKE_OFFER"
const OFFER_ACCEPTED="OFFER_ACCEPTED"
const PEER_NEGOTIATION_NEEDED="PEER_NEGOTIATION_NEEDED"
const PEER_NEGOTIATION_DONE="PEER_NEGOTIATION_DONE"
const CALL_CUT="CALL_CUT"
const ICE_CANDIDATE="ICE_CANDIDATE"
const SOME_ONE_SENDING_LIVE_LOCATION="SOME_ONE_SENDING_LIVE_LOCATION"
const SEND_LIVE_LOCATION_NOTIFICATION='SEND_LIVE_LOCATION_NOTIFICATION'
const REJECT_LIVE_LOCATION="REJECT_LIVE_LOCATION"
const LIVE_LOCATION_REQ_ACCEPTED="LIVE_LOCATION_REQ_ACCEPTED"
const SEND_LOCATION="SEND_LOCATION"
export {
    ALERT,
    REFETCH_CHATS,
    NEW_ATTACHMENTS,
    NEW_MESSAGES_ALERT,
    NEW_REQUEST,
    NEW_MESSAGE,
    START_TYPING,
    STOP_TYPING,
    CHAT_JOINED,
    CHAT_LEAVED,
    ONLINE_USERS,
    CALLING,
    SOMEONE_CALLING,
    CALL_ACCEPTED,
    CALL_REJECTED,
    TAKE_OFFER,
    OFFER_ACCEPTED,
    PEER_NEGOTIATION_NEEDED,
    PEER_NEGOTIATION_DONE,
    CALL_CUT,
    ICE_CANDIDATE,
    SEND_LIVE_LOCATION_NOTIFICATION,
    SOME_ONE_SENDING_LIVE_LOCATION,
    REJECT_LIVE_LOCATION,
    LIVE_LOCATION_REQ_ACCEPTED,
    SEND_LOCATION
}